dist: xenial
language: python

python:
  - "3.7"

services:
  - postgresql

env:
  - DJANGO_VERSION=2.2.3

before_script:
  - psql -c 'create database nokenku;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test
