# Generated by Django 2.2.4 on 2019-08-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_provinsi', models.IntegerField()),
                ('nama_provinsi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kabupaten', models.IntegerField()),
                ('nama_kabupaten', models.CharField(max_length=50)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Provinsi')),
            ],
        ),
    ]
