# Generated by Django 2.2.4 on 2019-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hasil_laut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id_rekening', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bank', models.CharField(max_length=150)),
                ('nama_rek', models.CharField(max_length=40)),
                ('nomor_rek', models.CharField(max_length=30)),
                ('gambar', models.ImageField(default='default.jpg', upload_to='rek')),
            ],
        ),
    ]
