# Generated by Django 2.2.4 on 2019-08-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_rekening'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=150)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal', models.DateTimeField()),
                ('id_username', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('alamat', models.CharField(max_length=250)),
                ('metode_pembayaran', models.CharField(max_length=20)),
                ('id_produk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Hasil_laut')),
                ('id_rekening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Rekening')),
            ],
        ),
    ]
